<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>ElfForestSaga.Android</RootNamespace>
    <ApplicationId>com.elves.forestsaga</ApplicationId>
    <ApplicationTitle>Elf Forest Saga Mobile</ApplicationTitle>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>
  </PropertyGroup>
</Project>
